name: dbt CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  dbt-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install dbt-postgres sqlfluff sqlfluff-templater-dbt

      - name: Lint SQL with SQLFluff
        run: sqlfluff lint dbt_project

      - name: Install dbt packages
        run: dbt deps
        working-directory: dbt_project

      - name: Run dbt tests
        run: dbt test
        working-directory: dbt_project